version: 1.0.{build}

configuration: Debug

clone_depth: 5

install:
  - git submodule update --init --recursive
  - call .\\build\\vs2013.bat

build:
  project: flair.sln
  parallel: true
  verbosity: minimal

test_script:
  - call .\\bin\\Debug\\tests.exe

notifications:
  - provider: Slack
    auth_token:
      secure: ChtIO8aIRsiIxV3qvebjV/mDk/DnPWaSm3yPXpvP8bKy4pz5dzJOtOWtlUFqzyyg
    channel: '#ci'
